//! Typed bindings for the Farmore home-chain contracts and ERC-20s, generated by
//! `alloy::sol!`. Declared inline (not from build artifacts) so the Rust build never
//! depends on Foundry having run first. These are shared by the node and the resolver.

use alloy::sol;

sol! {
    #[sol(rpc)]
    #[derive(Debug)]
    interface ISettlement {
        struct FarmoreOrderData {
            bytes32 recipientHandle;
            bytes32 asset;
            uint256 amount;
            uint64 destinationChainId;
            bytes32 destinationAsset;
            bytes32 recipientAddress;
        }
        struct OnchainCrossChainOrder {
            uint32 fillDeadline;
            bytes32 orderDataType;
            bytes orderData;
        }
        struct Output {
            bytes32 token;
            uint256 amount;
            bytes32 recipient;
            uint256 chainId;
        }
        struct FillInstruction {
            uint64 destinationChainId;
            bytes32 destinationSettler;
            bytes originData;
        }
        struct ResolvedCrossChainOrder {
            address user;
            uint256 originChainId;
            uint32 openDeadline;
            uint32 fillDeadline;
            bytes32 orderId;
            Output[] maxSpent;
            Output[] minReceived;
            FillInstruction[] fillInstructions;
        }

        function openIntent(OnchainCrossChainOrder order) external returns (bytes32 orderId);
        function assertFulfillment(bytes32 orderId, bytes32 handleId, address bondToken, uint256 bondAmount, bytes32 fillHash) external;
        function finalize(bytes32 orderId) external;
        function dispute(bytes32 orderId) external;
        function resolveDispute(bytes32 orderId, bool challengerWins) external;
        function statusOf(bytes32 orderId) external view returns (uint8);
        function challengeWindow() external view returns (uint64);
        function disputeBondBps() external view returns (uint256);
        function quoteReward(address bondToken, uint256 bondAmount) external view returns (uint256);
        function finalizableAt(bytes32 orderId) external view returns (uint64);
        function collateralToken() external view returns (address);
        function farToken() external view returns (address);

        event Open(bytes32 indexed orderId, ResolvedCrossChainOrder resolvedOrder);
        event IntentOpened(bytes32 indexed orderId, address indexed user, uint64 destinationChainId, uint32 fillDeadline);
        event Asserted(bytes32 indexed orderId, address indexed solver, bytes32 indexed handleId, address bondToken, uint256 bondAmount, bytes32 fillHash, uint64 finalizableAt);
        event Finalized(bytes32 indexed orderId, address indexed solver, bytes32 indexed handleId, uint256 minted);
    }

    #[sol(rpc)]
    #[derive(Debug)]
    interface INamespace {
        struct Account { address owner; uint64 defaultChainId; bytes32 defaultAddress; }
        function register(string handle) external returns (bytes32);
        function ownerOf(bytes32 node) external view returns (address);
        function nodeOf(string handle) external pure returns (bytes32);
        function resolve(string handle) external view returns (Account);
        function setDefaultReceiver(string handle, uint64 chainId, bytes32 addr) external;
    }

    #[sol(rpc)]
    #[derive(Debug)]
    interface IBondVault {
        function deposit(address token, uint256 amount) external;
        function withdraw(address token, uint256 amount) external;
        function freeBondOf(address solver, address token) external view returns (uint256);
        function bondOf(address solver, address token) external view returns (uint256);
    }

    #[sol(rpc)]
    #[derive(Debug)]
    interface IERC20Faucet {
        function approve(address spender, uint256 amount) external returns (bool);
        function transfer(address to, uint256 amount) external returns (bool);
        function balanceOf(address account) external view returns (uint256);
        function allowance(address owner, address spender) external view returns (uint256);
        function faucet(address to, uint256 amount) external;
        event Transfer(address indexed from, address indexed to, uint256 value);
    }
}
